language:
    - objective-c

before_install:
    - brew update

install:
    - brew install cmake

script:
    - mkdir _builds
    - cd _builds
    # download all
    - cmake ..
    # if run generate again, no download needed
    - cmake ..
